messaging:
  application-id: rest-show-interface
  stores:
    show: show-store
    url-to-show-id: url-to-showid-store
  topics:
    show: kissad-kiss-show
    show-private: kissad-private-restapi-show
    url-to-show-id: kissad-private-restapi-urltoshowid
    downloader-availability: kissad-downloader-availability

---

spring:
  profiles: dev

messaging:
  state-dir: ./target/streams-state-dir
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092

server:
  port: 15000

new-episode-poll: >
  0 0 14-18 * * MON-FRI,
  0 0 11 * * SAT,
  0 0 11 * * SUN,
  0 0 1-7 * * *