messaging:
  state-dir: ./target/streams-state-dir
  application-id: rest-show-interface
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092
  stores:
    show: show-store
  topics:
    show: kissad-show

server:
  port: 15000