messaging:
  state-dir: ./target/streams-state-dir
  purge-state-dir-before-start: true
  application-id: rest-show-interface
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092
  stores:
    show: show-store
  topics:
    show: kissad-kiss-show

server:
  port: 15000

new-episode-poll: >
  0 0 14-18 * * MON-FRI,
  0 0 11 * * SAT,
  0 0 11 * * SUN,
  0 0 1-7 * * *

