messaging.stream-config:
  application-id: ad.showFetch.hs

logging.level:
  com.gargoylesoftware.htmlunit: ERROR

---

spring:
  profiles: dev

messaging:
  stream-config:
    state-dir: ./target/streams-state-dir
    bootstrap-servers: 192.168.0.254:29092
  schema-registry-url: http://192.168.0.254:8081

com.horriblesubs:
  url: https://horriblesubs.info
  get-shows-endpoint: /api.php?method=getshows&type=show&showid=<SHOWID>