messaging:
  application-id: stream-rapidvideo-fetch
  topics:
    episode-link: kissad-ext-episodelink
    episode-download-link: kissad-download-episodelink

logging.level.com.gargoylesoftware.htmlunit: ERROR

---

spring:
  profiles: dev

messaging:
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092