messaging:
  state-dir: ./target/streams-state-dir
  application-id: stream-episode-fetch
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092
  stores:
    download-availability: downloader-availability
  topics:
    episode: kissad-kiss-episode
    episode-link: kissad-ext-episodelink
    downloader-availability: kissad-downloader-availability