messaging:
  application-id: stream-show-fetch
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092
  stores:
    downloaded-episode: kissad-download-finished-store
  topics:
    show: kissad-kiss-show
    episode: kissad-kiss-episode
    downloaded-episode: kissad-download-finished