messaging:
  application-id: stream-show-fetch
  stores:
    downloaded-episode: kissad-download-finished-store
  topics:
    show: kissad-kiss-show
    episode: kissad-kiss-episode
    downloaded-episode: kissad-download-finished

logging.level.com.gargoylesoftware.htmlunit: ERROR

---

spring:
  profiles: dev

messaging:
  state-dir: ./target/streams-state-dir
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092