kafka.streams.'application.id': ad.ui.server

kiss.captcha.request.application-id: ad.kissCaptchaCapture
---
spring:
  profiles: dev

messaging:
  schema-registry-url: http://192.168.0.254:8081

kafka:
  global.'bootstrap.servers': 192.168.0.254:29092
  streams.'state.dir': ./target/streams-state-dir

show.default:
  episode-name-pattern: S<SEASON_2>E<EPISODE_3>
  release-schedule-cron: 0 0 12 * * *

server:
  port: 15001

logging.level:
  org.springframework.web: DEBUG