messaging:
  cluster-connection:
    application.id: kiss-episode-fetch

logging.level.com.gargoylesoftware.htmlunit: ERROR

---

spring:
  profiles: dev

messaging:
  schema-registry-url: http://192.168.0.254:8081
  cluster-connection:
    state.dir: ./target/streams-state-dir
    bootstrap.servers: 192.168.0.254:29092

#kiss.captcha:
#  all-img-css-selector: "#container #formVerify1 img"
#  all-keyword-css-selector: "#container #formVerify1 span"