messaging:
  application-id: stream-episode-download
  topics:
    episode-download-link: kissad-download-episodelink
    downloader-availability: kissad-downloader-availability
    downloaded-episode: kissad-download-finished

logging.level.com.gargoylesoftware.htmlunit: ERROR

---

spring:
  profiles: dev

javax.net.ssl.trustStore: "/Users/grant/IdeaProjects/kiss-ad/keystore.123456"

download:
  destination: ./downloaded/
  attempts: 2

messaging:
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092
