messaging:
  stream-config:
    application-id: scheduler

---

spring:
  profiles: dev

messaging:
  stream-config:
    state-dir: ./target/streams-state-dir
    bootstrap-servers: 192.168.0.254:29092
  schema-registry-url: http://192.168.0.254:8081

show.default:
  episode-name-pattern: S<SEASON_2>E<EPISODE_3>
  release-schedule-cron: 0 0 12 * * *

server:
  port: 15000