kafka.streams.'application.id': ad.showFetch.sp.v2

logging.level:
  com.gargoylesoftware.htmlunit: ERROR

fetcher.type: SUBSPLEASE

org.subsplease:
  url: https://subsplease.org
  show-page:
    get-show-id-pattern: 'id="show-release-table"[^>]* sid="(\d+)"'
    get-episode-number-pattern: "(\\d+)$"
  get-show-endpoint: /api/?f=show&tz=America/New_York&sid=<SHOWID>

---
spring:
  profiles: dev

messaging:
  schema-registry-url: http://192.168.0.254:8081

kafka:
  global:
    'bootstrap.servers': 192.168.0.254:29092
