messaging:
  cluster-connection:
    application.id: stream-episode-fetch
  stores:
    download-availability: downloader-availability
  topics:
    episode: kissad-kiss-episode
    episode-link: kissad-ext-episodelink
    downloader-availability: kissad-downloader-availability

logging.level.com.gargoylesoftware.htmlunit: ERROR

---

spring:
  profiles: dev

messaging:
  schema-registry-url: http://192.168.0.254:8081
  cluster-connection:
    state.dir: ./target/streams-state-dir
    bootstrap.servers: 192.168.0.254:29092
