messaging:
  cluster-connection:
    application.id: stream-task-tester
    num.stream.threads: 1
    consumer.max.poll.records: 100


---
spring:
  profiles: dev

messaging:
  schema-registry-url: http://192.168.0.254:8081
  cluster-connection:
    state.dir: ./target/streams-state-dir
    bootstrap.servers: 192.168.0.254:29092
    acks: all

show.default:
  episode-name-pattern: S<SEASON_2>E<EPISODE_3>
  release-schedule-cron: 0 0 12 * * *

server:
  port: 15000