messaging:
  application-id: rest-show-interface
  stores:
    show: show-store-v2
  topics:
    show-store: ad.show.store

---

spring:
  profiles: dev

messaging:
  state-dir: ./target/streams-state-dir
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092

show.default:
  episode-name-pattern: S<SEASON_2>E<EPISODE_3>
  release-schedule-cron: 0 0 12 * * *

server:
  port: 15000