messaging:
  application-id: rest-show-interface
  stores:
    show: show-store
  topics:
    show-store: ad.store.show

---

spring:
  profiles: dev

messaging:
  state-dir: ./target/streams-state-dir
  schema-registry-url: http://192.168.0.254:8081
  brokers: 192.168.0.254:29092

server:
  port: 15000