rss-feed:
  url: https://nyaa.si/?page=rss&c=1_2&f=0


---
spring:
  profiles: dev

messaging:
  schema-registry-url: http://192.168.0.254:8081
  cluster-connection:
    bootstrap.servers: 192.168.0.254:29092

