messaging:
  cluster-connection:
    application.id: downloader

---
spring:
  profiles: dev

messaging:
  schema-registry-url: http://192.168.0.254:8081
  cluster-connection:
    bootstrap.servers: 192.168.0.254:29092

download:
  downloader-id: 1
  download-folder-root: "D:\\"
  overwrite-permission: true
  aria:
    temp-download-dir: "D:\\Unsorted"
    port: 9000
    path: "C:\\Users\\Grant\\Downloads\\aria2-1.34.0-win-64bit-build1\\aria2-1.34.0-win-64bit-build1\\aria2c.exe"
    status-poll-interval: 5s
    inactivity-timeout: 10m